Repository tyler-technologies-oss/forge-angular, pull requests merged in 2023-05, with the labels that each got.

#24 chore: remove node 14 support
  .github/workflows/build-release.yml
Labels: major

#25 chore: use trailing slash on publish directory path
  .autorc
Labels: major

#27 feat: updated workflows
  .github/workflows/auto-pr-check.yml
  .github/workflows/build-pr.yml
  .github/workflows/build-release.yml
  package-lock.json
Labels: minor

#28 docs: update changelog with breaking changes related to proxy components
  CHANGELOG.md
Labels: documentation, skip-release
