Repository tyler-technologies-oss/forge-angular, pull requests merged in 2024-11, with the labels that each got.

#67 fix(PopoverDirective): fixed a bug where dynamically created `<forge-popover>` elements could not be accessed when a `<forge-dialog>` element is open
  projects/forge-angular/src/lib/popover/popover.directive.ts
Labels: skip-release, patch

#70 feat(dialog): add elementInjector option to config
  projects/forge-angular/src/lib/dialog/dialog.service.ts
Labels: minor, skip-release

#69 chore: update proxies to match latest version of forge
  package-lock.json
  package.json
  projects/forge-angular/src/lib/app-bar/app-bar.component.ts
  projects/forge-angular/src/lib/date-picker/date-picker.component.ts
  projects/forge-angular/src/lib/date-range-picker/date-range-picker.component.ts
  projects/forge-angular/src/lib/list-item/list-item.component.ts
  projects/forge-angular/src/lib/skip-link/skip-link.component.ts
  projects/forge-angular/src/lib/tab-bar/tab-bar.component.ts
  projects/forge-angular/src/lib/tab/tab.component.ts
Labels: minor, skip-release

#68 fix(skip-link): expose skip link to public api
  projects/forge-angular/src/lib/forge.module.ts
  projects/forge-angular/src/lib/skip-link/index.ts
  projects/forge-angular/src/public-api.ts
Labels: patch
